### ISSUE TITLE
Error while building fastcard

### ISSUE THREAD

**Issue by MarcusFischerSFN** [swkrueger/Thrifty#3]
Hi there, great project!

as I am trying to -make- fastcard I am getting the following error:

> pi@rpi-rx1:~/build/fastcard $ make
[ 86%] Built target fastcard
[ 93%] Linking C executable fastcard
libfastcard.so: undefined reference to `rtlsdr_set_bias_tee'
collect2: error: ld returned 1 exit status
CMakeFiles/fastcard_bin.dir/build.make:98: recipe for target 'fastcard' failed
make[2]: *** [fastcard] Error 1
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/fastcard_bin.dir/all' failed
make[1]: *** [CMakeFiles/fastcard_bin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Do you have any idea why this is happening?

**Comment by swkrueger** [comment]
Hi. Thank you for your interest in Thrifty. The reason for this error is that I added support to fastcard for using a fork of librtlsdr with a software-controlled bias tee while working on a similar project for correlated antennas arrays (corx), and for some reason I set it as the default in the build file. It should be fixed now. Please let me know if you encounter any other issues.

**Comment by MarcusFischerSFN** [comment]
Hey thanks for your help, that did the job.

could you tell me how i should format the pos-rx.cfg file?

while doing thrifty tdoa  iam getting the error:

thrifty tdoa: error: argument -r/--rx-coordinates: can't open 'pos-rx.cfg': [Errno 2] No such file or directory: 'pos-rx.cfg‘

thanks a lot

Marcus


Am 20.02.2018 um 01:55 schrieb Schalk-Willem Krüger <notifications@github.com<mailto:notifications@github.com>>:


Hi. Thank you for your interest in Thrifty. The reason for this error is that I added support to fastcard for using a fork of librtlsdr with a software-controlled bias tee while working on a similar project for correlated antennas arrays (corx), and for some reason I set it as the default in the build file. It should be fixed now. Please let me know if you encounter any other issues.

**Comment by swkrueger** [comment]
The file `pos-rx.cfg` should contain the Cartesian coordinates of the receivers (in metres), one line per receiver, each line of the format `rxid: x [y] [z]`. For each line, the `rxid` should match the ID specified in the corresponding receiver's `detector.cfg` file or the ID passed to that receiver's fastdet instance.

For example, if you have three receivers and you are determining 2D positions, the file `pos-rx.cfg` could look like this:
```
0: 0.0 0.0
1: 5000.0 0.0
2: 2500.0 2000.0
```

**Comment by MarcusFischerSFN** [comment]
Thank you that did the job!
But unfortunately, I got more questions ☹


  *   I did capture signals of a vhf-tag for bats with 2 raspberry pi for about 2 minutes. They give a pulse every second, but when I do -thrifty match- there are no matches. Do you know why?
  *   How do you calibrate your rtl-sdr`s?
  *   Whats the pos-beacon.cfg?

Sorry to bother you…

Marcus

Von: Schalk-Willem Krüger <notifications@github.com>
Antworten an: swkrueger/Thrifty <reply@reply.github.com>
Datum: Mittwoch, 21. Februar 2018 um 03:45
An: swkrueger/Thrifty <Thrifty@noreply.github.com>
Cc: Marcus Fischer <m.fischer@sfn-planer.de>, Author <author@noreply.github.com>
Betreff: Re: [swkrueger/Thrifty] Error while building fastcard (#3)


The file pos-rx.cfg should contain the Cartesian coordinates of the receivers (in metres), one line per receiver, each line of the format rxid: x [y] [z]. For each line, the rxid should match the ID specified in the corresponding receiver's detector.cfg file or the ID passed to that receiver's fastdet instance.

For example, if you have three receivers and you are determining 2D positions, the file pos-rx.cfg could look like this:

0: 0.0 0.0

1: 5000.0 0.0

2: 2500.0 2000.0

**Comment by swkrueger** [comment]
>   *   I did capture signals of a vhf-tag for bats with 2 raspberry pi for about 2 minutes. They give a pulse every second, but when I do -thrifty match- there are no matches. Do you know why?

What does your signal look like? Thrifty detects and captures signals based on a PRN code. The template that is matched against during detection is set using the file named `template.npy` (for `thrifty detect`) or `template.tpl` (for fastdet) 

>   *   How do you calibrate your rtl-sdr`s?

With a transmitter at a fixed position, called a beacon.

>   *   Whats the pos-beacon.cfg?

The position of the beacon or beacons used for synchronisation.

The dissertation at https://hdl.handle.net/10394/25449 describes the use of PRN codes for matching and beacons for calibration in more detail. It also describes the context in detail.

**Comment by MarcusFischerSFN** [comment]
I used a beeper tag -I guess thats the correct name- sending a beep every second like in the picture I sent you.

As I guess I need one of those PRN code tags makes more testing unnecessary for today… :(

Do you think its possible to do that kind of position localization with beeper tags?

Marcus

[cid:21C5B111-E59F-411D-88EC-C3974FDBEAA3@fritz.box]

Am 22.02.2018 um 04:04 schrieb Schalk-Willem Krüger <notifications@github.com<mailto:notifications@github.com>>:


  *   I did capture signals of a vhf-tag for bats with 2 raspberry pi for about 2 minutes. They give a pulse every second, but when I do -thrifty match- there are no matches. Do you know why?

What does your signal look like? Thrifty detects and captures signals based on a PRN code. The template that is matched against during detection is set using the file named template.npy (for thrifty detect) or template.tpl (for fastdet)

  *   How do you calibrate your rtl-sdr`s?

With a transmitter at a fixed position, called a beacon.

  *   Whats the pos-beacon.cfg?

The position of the beacon or beacons used for synchronisation.

The dissertation at https://hdl.handle.net/10394/25449 describes the use of PRN codes for matching and beacons for calibration in more detail. It also describes the context in detail.

**Comment by swkrueger** [comment]
> Do you think its possible to do that kind of position localization with beeper tags?

It depends on the waveform of the signal (I didn't receive any pictures). If it a signal with low spectral density at high frequencies or with bad autocorrelation properties, then no. You will be able to detect the presence of the signals, but won't be able to obtain an accurate estimate of the arrival time. However, depending on the hardware, it might be possible to modify the beeper tag to modulate a PRN code.
